# Form implementation generated from reading ui file 'langton.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Langton(object):
    def setupUi(self, Langton):
        Langton.setObjectName("Langton")
        Langton.resize(650, 600)
        Langton.setMinimumSize(QtCore.QSize(250, 100))
        self.centralwidget = QtWidgets.QWidget(parent=Langton)
        self.centralwidget.setMinimumSize(QtCore.QSize(300, 200))
        self.centralwidget.setObjectName("centralwidget")
        self.canvas = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(0, 0, 256, 192))
        self.canvas.setObjectName("canvas")
        Langton.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Langton)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 30))
        self.menubar.setObjectName("menubar")
        self.menuMainmenu = QtWidgets.QMenu(parent=self.menubar)
        self.menuMainmenu.setObjectName("menuMainmenu")
        self.menuEdit_menu = QtWidgets.QMenu(parent=self.menubar)
        self.menuEdit_menu.setObjectName("menuEdit_menu")
        self.menuSimu_menu = QtWidgets.QMenu(parent=self.menubar)
        self.menuSimu_menu.setObjectName("menuSimu_menu")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Langton.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Langton)
        self.statusbar.setObjectName("statusbar")
        Langton.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(parent=Langton)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtGui.QAction(parent=Langton)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSetup = QtGui.QAction(parent=Langton)
        self.actionSetup.setObjectName("actionSetup")
        self.actionStart = QtGui.QAction(parent=Langton)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtGui.QAction(parent=Langton)
        self.actionStop.setObjectName("actionStop")
        self.actionAbout = QtGui.QAction(parent=Langton)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_Qt = QtGui.QAction(parent=Langton)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.menuMainmenu.addAction(self.actionSave)
        self.menuMainmenu.addAction(self.actionQuit)
        self.menuEdit_menu.addAction(self.actionSetup)
        self.menuSimu_menu.addAction(self.actionStart)
        self.menuSimu_menu.addAction(self.actionStop)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuMainmenu.menuAction())
        self.menubar.addAction(self.menuEdit_menu.menuAction())
        self.menubar.addAction(self.menuSimu_menu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Langton)
        QtCore.QMetaObject.connectSlotsByName(Langton)

    def retranslateUi(self, Langton):
        _translate = QtCore.QCoreApplication.translate
        Langton.setWindowTitle(_translate("Langton", "Langton"))
        self.menuMainmenu.setTitle(_translate("Langton", "&File"))
        self.menuEdit_menu.setTitle(_translate("Langton", "&Edit"))
        self.menuSimu_menu.setTitle(_translate("Langton", "&Simulation"))
        self.menuHelp.setTitle(_translate("Langton", "&Help"))
        self.actionSave.setText(_translate("Langton", "&Save"))
        self.actionSave.setShortcut(_translate("Langton", "Ctrl+S"))
        self.actionQuit.setText(_translate("Langton", "&Quit"))
        self.actionQuit.setShortcut(_translate("Langton", "Ctrl+Q"))
        self.actionSetup.setText(_translate("Langton", "Setup"))
        self.actionStart.setText(_translate("Langton", "Start"))
        self.actionStop.setText(_translate("Langton", "Stop"))
        self.actionAbout.setText(_translate("Langton", "&About"))
        self.actionAbout_Qt.setText(_translate("Langton", "About Qt"))
